PARTICIPATION_FEE = 200
ATTENTION_BONUS = -99
BUDGET = 110 

TRUST_ROUNDS = 3
COORDINATION_ROUNDS = 3
MARKET_ROUNDS = 3

TRUST_ENDOWMENT = 40
MARKET_ENDOWMENT = 20
MARKET_ENTRY_FEE = 20
MARKET_WIN = 50
MARKET_LOSS = 0
COORDINATION_SUCCESS = 30
COORDINATION_PREFERENCE = 10

AUTOFILL = False
TESTING = True
GOTHROUGH = False
#URL = "https://bahnik.pythonanywhere.com/"
URL = "TEST"
#URL = "http://127.0.0.1:8000/"