PARTICIPATION_FEE = 200
ATTENTION_BONUS = 10
QUIZ_BONUS = 5
POSTDICTION_BONUS = 20

AUTOFILL = False
TESTING = False
GOTHROUGH = False
URL = "https://bahnik.pythonanywhere.com/"
#URL = "TEST"
#URL = "http://127.0.0.1:8000/"